---
title: "ST509_Midterm_HJ"
author: "Hwijun Kwon"
date: "2024-04-20"
header-includes:
   - \usepackage{multirow}
output:
  pdf_document: default
  word_document: default
---

# 1. Introduction

$$
y_i |x_i \sim{} Poisson(\mu_{\beta}(x_i))
$$

# 2. Competing Methods

## Poisson Regression

## 1. Unpenalized Poisson Regression

```{r}
my_poi <- function(X, y, init = NULL, max_iter = 1000, eps = 1e-5) {
  # Scaling
  y_sd <- sd(y); X_sd <- apply(X, 2, sd)
  y <- y /y_sd; X <- t(t(X)/ X_sd)
  # Add intercept term
  X <- cbind(1, X) ; n <- nrow(X); p <- ncol(X) 
  # INIT
  if (is.null(init)) init <- rep(0, p);
  beta <- init 
  # Iteration
  for (iter in 1:max_iter) {
    eta <- X %*% beta
    w <- exp(eta) # Mean = Variance
    
    # Limit w 
    w <- pmin(w, 1e6)
    w <- pmax(w, 1e-6)
    
    z <- eta + (y-w)/w
    # IRLS
    X_tilde <- diag(c(sqrt(w))) %*% X
    z_tilde <- diag(c(sqrt(w))) %*% z
    qr_obj <-  qr(X_tilde)
    new_beta <- backsolve(qr_obj$qr, qr.qty(qr_obj, z_tilde)) # Check Convergence
  if (max(abs(new_beta - beta))/ max(abs(beta)) < eps) break
    beta <- new_beta
  }
  # Warning
  if (iter == max_iter) warning("Algorithm may not have converged!")
  # Restore beta coef
  beta <- c(beta) * c(1, 1/X_sd) + c(log(y_sd), rep(0, p-1))
  # Result
  list(X_tilde = dim(X_tilde), est = t(beta), iterations = iter)
}
```

```{r}
library(MASS)
generate_data <- function(n,p,nu) {
  mu <- rep(0, p)
  sigma <- outer(1:p, 1:p, FUN = function(i, j) nu^(abs(i-j)))
  x <- mvrnorm(n=n, mu=mu, Sigma=sigma)
  mu_x <- exp(1 + x %*% beta) # add intercept
  y <- rpois(n, mu_x)
  return(list(x = x, y = y))
}

train_data <- generate_data(500, 50, 0.7)
y <- train_data$y ; x <-train_data$x
my_poi(x, y, init = rep(3, 51))
```

#3. Simulation Set Up

```{r}
library(MASS)
seed = 202402040
generate_data <- function(n, p, nu, seed) {
  set.seed(seed)
  mu <- rep(0, p)
  sigma <- outer(1:p, 1:p, FUN = function(i, j) nu^(abs(i-j)))
  x <- mvrnorm(n=n, mu=mu, Sigma=sigma)
  
  
  beta0 = 1
  beta = c(rep(1,3), rep(0, p-3))
  mu_x <- exp(beta0 + x %*% beta)
  e <- rnorm(n, 0, 0.5)
  
  y <- rpois(n, mu_x) + e
  
  return(list(x = x, y = y))
}

data = vector('list', 100)
seed = 2024020409
for (i in 1:100){
  data[[i]] = generate_data()
}
```

$$
\begin{array}{|c|c|c|ccc|ccc|c|}
\hline
\rho & p & \text{Methods} & \multicolumn{3}{c|}{\text{Estimation Accuracy}} & \multicolumn{3}{c|}{\text{Selection Performance}} & \text{Computing Time} \\
\hline
0 & 3 & \text{Logit} & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\
\hline
\end{array}
$$

\$\$

```{=tex}
\begin{table}[!htbp]
\begin{center}
\begin{adjustbox}{max width=\textwidth}
\begin{tabular} {| c|c|c | ccc | ccc |c|} \hline
\multirow{2}*{$\rho$}  & 
\multirow{2}*{$p$}     & 
\multirow{2}*{Methods} & \multicolumn{3}{c|}{Estimation Accuracy}
                       & \multicolumn{3}{c|}{Selection Performance}
                       & Computing \\  \cline{4-9}
& & & MSE & Var & Bias & CS & IS & AC & Time \\ \hline
                       
\multirow{10}*{0} & 
    \multirow{5}*{3} 
      & Logit & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Ridge & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Lasso & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Elast & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\                          
    & & SCAD  & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\ \cline{2-10}
    &
    \multirow{5}*{50} 
      & Logit & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Ridge & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Lasso & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Elast & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\                          
    & & SCAD  & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\ \hline

\multirow{10}*{0.7} & 
    \multirow{5}*{3} 
      & Logit & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Ridge & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Lasso & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Elast & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\                          
    & & SCAD  & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\ \cline{2-10}
    &
    \multirow{5}*{50} 
      & Logit & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Ridge & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Lasso & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\  
    & & Elast & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\                          
    & & SCAD  & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) & 000 (000) \\ \hline
    
\end{tabular}
\end{adjustbox}
\end{center}
\caption{Caption Here}

\end{table}
```
\$\$

```{r, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)

# 임의의 데이터 프레임 생성
data <- data.frame(
  rho = c(rep(0, 5), rep(0.7, 5)),
  p = rep(c(3, 50), each = 5),
  Methods = rep(c("Logit", "Ridge", "Lasso", "Elast", "SCAD"), 2),
  MSE = "000 (000)",
  Var = "000 (000)",
  Bias = "000 (000)",
  CS = "000 (000)",
  IS = "000 (000)",
  AC = "000 (000)",
  Time = "000 (000)"
)

# kable을 사용하여 기본 테이블 생성
kable_styling(
  kable(data, "latex", booktabs = TRUE, linesep = "") %>%
    add_header_above(c(" " = 2, "Estimation Accuracy" = 3, "Selection Performance" = 3, " " = 1)) %>%
    kable_styling(latex_options = c("striped", "scale_down")),
  font_size = 7
)
```
