---
title: "ST509_HW3_2024020409"
author: "Hwijun Kwon"
date: "2024-03-29"
output: pdf_document
---


# 1
```{r Soft Threshold Operator}
# MY
S <- function(z, lambda){
    sign(z) * max(abs(z) - lambda, 0)
}
# Prof
S <- function(z, lambda) {    # set soft-thresholding function
  (z - lambda) * (z > lambda) + (z + lambda) * (z < -lambda) + 0 * (abs(z) <= lambda)
}

S(z = 3,lambda = 10)
```

```{r}
cd.lasso <- function(x, y, lambda){
  # centering y and standardizing X
  z <- scale(x)
  m <- attr(z, "scaled:center") # save original mean X
  s <- attr(z, "scaled:scale") # save original scale of Y
  u <- (y-mean(y))
  print(paste("m is", m))
  print(paste("s is", s))
  print(paste("Y is", y))
  #initialization
  beta <- coef(lm(u ~ z - 1))  # -1 : exclude intercept 
  r <- u - z %*% beta 
  
  for (iter in 1:100) {
    new.beta <- beta
    # coordinate 1 to p
    for (j in 1:p){
      # Update coefficients
      temp <- beta[j] + crossprod(z[, j], r)/n
      new.beta[j] <- S(temp, lambda/s[j])
      # Update residuals
      r <- r - (new.beta[j] - beta[j]) * z[, j]
    }
    
    delta <- max(abs(new.beta - beta))
    if (delta < 1.0e-3) break
    beta <- new.beta
  }
  
  # Transform back to the original scale
  beta <- new.beta/s
  beta0 <- mean(y) - crossprod(beta, m)
  c(beta)

}
cd.lasso(x, y, lambda = 0.1)
```

```{r}
cd.lasso <- function(x, y, lambda){
  # CD algorithm for lasso    # marginal standardization of x
  n <- length(y); p <- nrow(x)
  s <- sqrt(apply(x^2, 2, sum)/n) # sd of each row
  z <- t(t(x)/s)  # marginal standarization of x (by row )
  print(paste("n is", n))
  print(paste("s is", s))
  print(paste("z is", z))
  print(s)
  apply(z^2, 2, sum)
  # initialization
  beta <- coef(lm(y ~ z - 1)); r <- y - z %*% beta
  
  for (iter in 1:100) {
    new.beta <- beta
    for (j in 1:p) {
      temp <- beta[j] + crossprod(z[,j], r)/n
      new.beta[j] <- S(temp, lambda/s[j]) 
      r <- r - (new.beta[j] - beta[j]) * z[,j]
    }
    delta <- max(abs(new.beta - beta))
    if (delta < 1.0e-3) break
    beta <- new.beta
  }
  beta <- new.beta/s
  c(beta)
}
cd.lasso(x, y, lambda = 0.1)
```


```{r Simulated Data for CD}
set.seed(1) ; n <- 100 ; p <- 5
x <- matrix(rnorm(n*p, 1, 1), n, p) # X : 100 * 5 matrix
e <- rnorm(n, 0, 0.5) # noise

true.beta <- rep(0, p+1) ;
true.beta[1] <- 1 # intercept
true.beta[2:(p+1)] <- c(rep(1, 3), rep(0, p-3))
true.beta

y <- true.beta[1] + x %*% true.beta[-1] + e

```
```{r}
library(glmnet)
est0 <- coef(lm(y ~ x))
est1 <- cd.lasso(x, y, lambda = 0.1)
est2 <- coef(glmnet(x, y, lambda = 0.1, standardize = F))

result <- cbind(true.beta, est0, est1, est2)
colnames(result) <- c("true", "lm", "ours", "glmnet")
rownames(result) <- 0:p
print(round(result, 4))
```

## (A)


```{r}
#pd.elastic <- function()

```

### (by glmnet)
```{r}
train <- matrix(scan("train.txt"), 500, 51)
test  <- matrix(scan("test.txt"), 500, 51)
x <- train[,-51] ; y <- train[,51]
x.test <- test[,-51]
y.test <- test[,51]
```

```{r}
library(glmnet)
alpha = 0.5 # alpha for elastic net

```
